name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install

      - name: Instalar binário do Cypress
        run: npx cypress install

      - name: Corrigir permissão
        run: chmod +x node_modules/.bin/cypress

      - name: Rodar testes
        run: npx cypress run
